CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y
CONFIG_PMW3610_ALT=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y

CONFIG_ZMK_POINTING_LOG_LEVEL=4   # максимум логов
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
